### ISSUE TITLE
client=_client.withAuthClient(auth); 

### ISSUE THREAD

**Issue by devans1964** [omriiluz/gdrive-sync#1]
I have authorised the client and the appropriate token is in the .gsync directory,

However on running a sync, I get the following error
/Users/dave/RubymineProjects/archive-node/upload-1.js:298
    client=_client.withAuthClient(auth); 
                   ^
TypeError: Object #<GoogleApisClient> has no method 'withAuthClient'

**Comment by omriiluz** [comment]
Please try the latest version, should be fixed. It was due to google changing the API.
